apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cherenkov
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: cherenkov
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cherenkov-api
      namespace: cherenkov
    - apiVersion: apps/v1
      kind: Deployment
      name: cherenkov-ingest
      namespace: cherenkov
    - apiVersion: apps/v1
      kind: Deployment
      name: cherenkov-web
      namespace: cherenkov
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cherenkov
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tworjaga/cherenkov
  ref:
    branch: main
  secretRef:
    name: github-token
