apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cherenkov

resources:
- namespace.yaml
- configmap.yaml
- api-deployment.yaml
- ingest-deployment.yaml
- stream-deployment.yaml
- web-deployment.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cherenkov
  app.kubernetes.io/managed-by: flux

images:
- name: ghcr.io/tworjaga/cherenkov-api
  newTag: latest
- name: ghcr.io/tworjaga/cherenkov-ingest
  newTag: latest
- name: ghcr.io/tworjaga/cherenkov-stream
  newTag: latest
- name: ghcr.io/tworjaga/cherenkov-web
  newTag: latest
