apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cherenkov-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: cherenkov-api
    newTag: staging
  - name: cherenkov-ingest
    newTag: staging
  - name: cherenkov-stream
    newTag: staging
  - name: cherenkov-web
    newTag: staging

replicas:
  - name: api-deployment
    count: 1
  - name: ingest-deployment
    count: 1
  - name: stream-deployment
    count: 1
  - name: web-deployment
    count: 1
